/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IRainInterpreterIntegrityInterface extends utils.Interface {
  functions: {
    "ensureIntegrity(bytes[],uint256,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ensureIntegrity",
    values: [BytesLike[], BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "ensureIntegrity",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRainInterpreterIntegrity extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRainInterpreterIntegrityInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ensureIntegrity(
      sources: BytesLike[],
      constantsLength: BigNumberish,
      minStackOutputs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        contextReads: BigNumber;
        stackLength: BigNumber;
      }
    >;
  };

  ensureIntegrity(
    sources: BytesLike[],
    constantsLength: BigNumberish,
    minStackOutputs: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { contextReads: BigNumber; stackLength: BigNumber }
  >;

  callStatic: {
    ensureIntegrity(
      sources: BytesLike[],
      constantsLength: BigNumberish,
      minStackOutputs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        contextReads: BigNumber;
        stackLength: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    ensureIntegrity(
      sources: BytesLike[],
      constantsLength: BigNumberish,
      minStackOutputs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ensureIntegrity(
      sources: BytesLike[],
      constantsLength: BigNumberish,
      minStackOutputs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
